name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (poetry)
        run: |
          pip install poetry
          python -m poetry lock
          python -m poetry install

      - name: Format (ruff)
        run: |
          poetry run ruff format murmura

      - name: Lint (ruff)
        run: |
          poetry run ruff check murmura --output-format=github
        continue-on-error: false

      - name: Type checks (mypy)
        run: |
          poetry run mypy -p murmura

      - name: Test (pytest)
        run: |
          poetry run pytest -v --cov=murmura

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: Coveragenator
          path: python-coverage-comment-action.txt